language: node_js
node_js:
  - "11"
branches:
  only:
  - master
cache:
  directories:
  - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_1a092584ba06_key -iv $encrypted_1a092584ba06_iv -in id_rsa.enc -out id_rsa -d
  - chmod 600 id_rsa
  - eval $(ssh-agent)
  - ssh-add id_rsa

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo clean
  - hexo g
  - hexo g

after_success:
  - hexo deploy
