language: node_js
node_js:
 - '11'
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_4ec34457a726_key -iv $encrypted_4ec34457a726_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 id_rsa
- eval $(ssh-agent)
- ssh-add id_rsa
- git add .
- git commit -m 'add id_rsa'
install:
  - npm install -g hexo-cli
  - npm install
script:
  - hexo clean
  - hexo g
after_success:
  - hexo deploy
notifications:
  email:
   - haihuiling2014@gmail.com
addons:
  ssh_known_hosts: 123.56.24.251
