language: node_js
node_js:
 - 11
branches:
  only:
  - /^\d\.\d\.\d/
  - master
cache:
  directories:
    - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_1a092584ba06_key -iv $encrypted_1a092584ba06_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
install:
  - npm install -g hexo-cli
  - npm install
script:
  - hexo clean
  - hexo g
after_success:
  - hexo deploy
notifications:
  email:
   - haihuiling2014@gmail.com
addons:
  ssh_known_hosts:
  - 39.105.199.208
  - 49.234.18.99